### ISSUE TITLE
Result comparation between with and without distributed training

### ISSUE THREAD

**Issue by asheroin** [caopulan/GANInverter#2]
Would you please offer some image invertion comparation on distributed trained model and official pretrain model, like in e4e framework? Afraid that distributed training would effect the final result due to big batch size for training speedup.
   
Also, for distributed training usage, a training parameter suggestion would be very helpful if anyone want to follow this work. Hope for those information!

**Comment by caopulan** [comment]
> Would you please offer some image invertion comparation on distributed trained model and official pretrain model, like in e4e framework? Afraid that distributed training would effect the final result due to big batch size for training speedup.
> 
> Also, for distributed training usage, a training parameter suggestion would be very helpful if anyone want to follow this work. Hope for those information!

We have not conducted a complete distributed training. We tried to train e4e and pSp with large batch size but convergence was not accelerated, which is the reason we explain in the readme. We may later take more experiments to see the impacts of distributed training. Glad to receive any suggestions.

**Comment by asheroin** [comment]
> 



> > Would you please offer some image invertion comparation on distributed trained model and official pretrain model, like in e4e framework? Afraid that distributed training would effect the final result due to big batch size for training speedup.
> > Also, for distributed training usage, a training parameter suggestion would be very helpful if anyone want to follow this work. Hope for those information!
> 
> We have not conducted a complete distributed training. We tried to train e4e and pSp with large batch size but convergence was not accelerated, which is the reason we explain in the readme. We may later take more experiments to see the impacts of distributed training. Glad to receive any suggestions.

Actually I had implemented distributed training support for offical e4e repos and found smillar conclutions and still had no idea how to figure such a problem.

**Comment by caopulan** [comment]
> > 
> 
> > > Would you please offer some image invertion comparation on distributed trained model and official pretrain model, like in e4e framework? Afraid that distributed training would effect the final result due to big batch size for training speedup.
> > > Also, for distributed training usage, a training parameter suggestion would be very helpful if anyone want to follow this work. Hope for those information!
> > 
> > 
> > We have not conducted a complete distributed training. We tried to train e4e and pSp with large batch size but convergence was not accelerated, which is the reason we explain in the readme. We may later take more experiments to see the impacts of distributed training. Glad to receive any suggestions.
> 
> Actually I had implemented distributed training support for offical e4e repos and found smillar conclutions and still had no idea how to figure such a problem.

Training techniques have not been explored now in inversion task. All encoders almost use pSp-style training process. Distributed training, optimizer and hyper-parameters, or even model architecture are under-researched.
